import {getCustomSuites} from "./getCustomSuites.mjs";
import {getAutoGeneratedSuites} from "./getAutoGeneratedSuites.mjs";
import {mergeSuites} from "./mergeSuites.mjs";
import {OUT_PATH} from "./constants.mjs";
import fs from 'fs';

console.info('Suites generator: Start.');

const customSuites = getCustomSuites();
const autoGeneratedSuites = getAutoGeneratedSuites();

const suites = mergeSuites(customSuites, autoGeneratedSuites);
fs.writeFileSync(OUT_PATH, JSON.stringify(suites, null, 2));

console.info(`Suites generator: Finish. File with all suits in "${OUT_PATH}".`);
