export const mergeSuites = (customSuites, autoGeneratedSuites) => {
    let suites = {
        ...customSuites,
        ...autoGeneratedSuites
    };

    Object.keys(customSuites).forEach((customSuiteName) => {
        if (autoGeneratedSuites[customSuiteName]) {
            console.warn(`mergeSuites: Name "${customSuiteName}" for custom and auto generated suites matched.`);

            suites[customSuiteName] = [
                ...autoGeneratedSuites[customSuiteName],
                ...customSuites[customSuiteName]
            ];

            suites[customSuiteName] = [...new Set(suites[customSuiteName])];
        }
    });

    return suites;
};
