export enum Discipline {
  RESEARCH = 'RESEARCH',
  UX_AND_DESIGN = 'UX_AND_DESIGN',
  DEVELOPMENT = 'DEVELOPMENT',
  DEVOPS = 'DEVOPS',
  DATAOPS = 'DATAOPS',
  CYBERSECURITY = 'CYBERSECURITY',
  CLOUD_COMPUTING_AND_HPC = 'CLOUD_COMPUTING_AND_HPC',
  BLOCKCHAIN = 'BLOCKCHAIN'
}
